### PR TITLE
3.0

### LINKED ISSUE #5: Set stereo to false
When I ran this example, the stereo flag was set to true when it printed out, which doubled the bandwidth.  Stereo makes no sense if you have a single microphone.  Do you know how to switch it off?  

(I've also filed this issue at the demo projects repo: https://github.com/godotengine/godot-demo-projects/issues/470 )

### LINKED ISSUE #6: Update 3.2.4 / 4.0  -> real time VoIP
Can you update this cool project to the newest Godot version (Realese Candidate) which supports realtime VoIP data?
(see: https://github.com/godotengine/godot/pull/45593)

Gamemap

### PR DESCRIPTION
**Pull request by ikbencasdoei**
Updated to use the new merged AudioEffectCapture godotengine/godot#45593. (fixes #6)

Other changes and improvements include:
- Voice is now transmitted every frame, improving delays and interruptions.
- Incoming voice frames are played directly using an AudioStreamGenerator instead of using individual AudioStreamSamples, eliminating pops but introducing a delay.
- Transmitted voice is mono instead of stereo, improving bandwidth. (fixes  #5)
- Fixed memory leak associated with AudioEffectRecord.
- Audio is transmitted using PoolRealArrays (32 bit).
- Compatible with other mix rates.
- Demo UI refactoring and improvements.
- Added listen mode for testing and exported a few more variables.
- Added input threshold parameter.
- Added client/server IP and port inputs for demo

Any feedback is greatly appreciated!

### CODE REVIEW

**Comment by havi05** [comment]
Is this lagging a bug or my bad microphone? (enable sound on video player)

https://user-images.githubusercontent.com/71942164/109341883-55211f80-786b-11eb-830d-f1ee929a8ec0.mp4

**Comment by ikbencasdoei** [comment]
Yeah that's a bug. Its worse than I expected. Probably have to look into this further.

**Comment by havi05** [comment]
Ok, I am glad that the real time transmission works so well.

EDIT: I really like the Listen feature. Thank you!

**Comment by ikbencasdoei** [comment]
Updated to use AudioStreamGenerator instead of using AudioStreamSamples.

**Comment by havi05** [comment]
The sound works very well. Is the latency a bit greater?

**Comment by ikbencasdoei** [comment]
Not sure why, but the AudioStreamGenerator does that.

**Comment by ikbencasdoei** [comment]
https://github.com/casbrugman/godot-voip/pull/7#issuecomment-787119945 https://github.com/casbrugman/godot-voip/pull/7#issuecomment-787124448 Another thing for the Godot team to fix. 😏 But for now I think it is worth it.

**Comment by havi05** [comment]
Ok, thank you for this voice chat.

**Comment by havi05** [comment]
https://github.com/casbrugman/godot-voip/pull/7#issuecomment-787129273 Is there already an issue or could you create one?

**Comment by ikbencasdoei** [comment]
I will create one

**Comment by havi05** [comment]
Unfortunately, the latency is still (just a bit) greater than with the AudioStreamSamples, but I'm glad it's faster than before 3.2.4. So I can use it better now.

Thank you for this great, cool, usefull, impressive, wounderful Addon!
**<3**

**Comment by havi05** [comment]
If it is _**possible**_ and you have enough _**time**_ and _**fun**_, it would be great if this low latency could also be fixed.

**Comment by ikbencasdoei** [comment]
I'm planning on fixing it in the next version

**Pull request merged**
